name: ModsDownload
on: 
  workflow_dispatch:
jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      - name: Build Downloader
        run: dotnet publish ${GITHUB_WORKSPACE}/runners/CurseforgeDownloader/CurseforgeDownloader/CurseforgeDownloader.csproj -c Release -o ${GITHUB_WORKSPACE}/ -r linux-x64 --self-contained false -p:PublishSingleFile=true

      - name: Run Downloader
        run: |
          mkdir ${GITHUB_WORKSPACE}/mods
          chmod +x ${GITHUB_WORKSPACE}/CurseforgeDownloader
          ${GITHUB_WORKSPACE}/CurseforgeDownloader --api-key '${{ secrets.OVERWOLF_API_KEY }}' --mod-folder-path './mods' --black-list '454215'

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: Herodotus-Mods
          path: mods
          retention-days: 5
